name: CI

on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Save state
      run: echo "{name}={value}" >> $GITHUB_STATE

    - name: Set output
      run: echo "{name}={value}" >> $GITHUB_OUTPUT
    - uses: actions/checkout@v3
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - name: Setup Nuget.exe for use with actions
      uses: Nuget/Setup-nuget@v1.0.2
    - name: Restore Nuget Packages
      run: nuget restore solution.sln
    - name: Build Solution
      run: msbuild solution.sln
