name: CI

on: [push]
 
jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      run: nuget restore Quest2-VRC.sln
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with MSBuild
      run: msbuild  Quest2-VRC.sln -p:Configuration=Release
