name: CI

on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Save state
      run: echo "{name}={value}" >> $GITHUB_STATE
    - name: Set output
      run: echo "{name}={value}" >> $GITHUB_OUTPUT
    - uses: actions/checkout@v3
    - name: Install .NET 7 SDK
      uses: actions/setup-dotnet@v3
      with:
           dotnet-version: 7.x.x
      env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Restore Nuget Packages
      run: dotnet restore Quest2-VRC.sln
    - name: Build Solution (Release)
      run: dotnet build Quest2-VRC.sln --configuration Release --no-restore
    - name: Build Solution (Debug)
      run: dotnet build Quest2-VRC.sln --configuration Debug --no-restore
    - name: Upload Artifact (Release)
      uses: actions/upload-artifact@v3
      with:
        name: Release
        path: Quest2-VRC.GUI\bin\Release\
        retention-days: 5
    - name: Upload Artifact (Debug)
      uses: actions/upload-artifact@v3
      with:
        name: Debug
        path: Quest2-VRC.GUI\bin\Debug\
        retention-days: 5
    - name: Upload Artifact (Debug Core DLL)
      uses: actions/upload-artifact@v3
      with:
        name: 'Debug Core DLL'
        path: Quest2-VRC\bin\Debug\
        retention-days: 5   
    - name: Upload Artifact (Release Core DLL)
      uses: actions/upload-artifact@v3
      with:
        name: 'Release Core DLL'
        path: Quest2-VRC\bin\Release\
        retention-days: 5       
