name: CI

on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Save state
      run: echo "{name}={value}" >> $GITHUB_STATE

    - name: Set output
      run: echo "{name}={value}" >> $GITHUB_OUTPUT
    - uses: actions/checkout@v3
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
      env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Setup Nuget.exe for use with actions
      uses: Nuget/Setup-nuget@v1.0.2
      env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Restore Nuget Packages
      run: nuget restore Quest2-VRC.sln
    - name: Build Solution
      run: msbuild Quest2-VRC.sln
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: my_file.txt
        retention-days: 5
