name: CI

on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Save state
      run: echo "{name}={value}" >> $GITHUB_STATE

    - name: Set output
      run: echo "{name}={value}" >> $GITHUB_OUTPUT
    - uses: actions/checkout@v3
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
      env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Setup Nuget.exe for use with actions
      uses: Nuget/Setup-nuget@v1.0.2
      env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Restore Nuget Packages
      run: nuget restore Quest2-VRC.sln
    - name: Build Solution
      run: msbuild Quest2-VRC.sln /t:Build /p:Configuration=Release
    - name: Build Solution
      run: msbuild Quest2-VRC.sln /t:Build /p:Configuration=Debug
    - name: 'Upload Artifact (Release)'
      uses: actions/upload-artifact@v3
      with:
        name: Release
        path: Quest2-VRC.GUI\bin\Release\
        retention-days: 5
    - name: 'Upload Artifact (Debug)'
      uses: actions/upload-artifact@v3
      with:
        name: Debug
        path: Quest2-VRC.GUI\bin\Debug\
        retention-days: 5
